# Netlify Configuration for Fluxr

[build]
  # Build command
  command = "npm run build"
  # Directory with the built files
  publish = "dist"
  # Functions directory if you add Netlify Functions later
  functions = "netlify/functions"

# Configure secret scanning to ignore specific keys
[secrets]
  scan_omit_keys = [
    "SUPABASE_REGION"
  ]

# Branch-specific settings
[context.main]
  [context.main.secrets]
    scan_omit_keys = [
      "SUPABASE_REGION"
    ]

[context.beta]
  [context.beta.secrets]
    scan_omit_keys = [
      "SUPABASE_REGION"
    ]

# SPA redirect rule - this ensures all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Environment variable inheritance
[build.environment]
  NODE_VERSION = "20"
  VITE_MIXPANEL_TOKEN = "cc245e521eca3af89d7063811a233f53"

# Set cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"