name: Sync Beta with Main

on:
  push:
    branches:
      - main

jobs:
  sync-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - name: Sync Beta with Main
        run: |
          git fetch origin
          git checkout beta
          git reset --hard origin/main
          git push origin beta --force 